apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-deployment
  labels:
    app: simple-flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-flask-deployment
  template:
    metadata:
      labels:
        app: simple-flask-deployment
    spec:
      containers:
        - name: simple-flask-container
          image: 'guigo13/flasktry:v6'
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: simple-flask-service
  labels:
    name: simple-flask-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: simple-flask-container
  type: LoadBalancer
