apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-nginx-gke
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-nginx-gke
    spec:
      containers:
        - name: simple-nginx-gke
          image: 'guigo13/simple-nginx-gcp-image:v1'
          ports:
            - containerPort: 80
